# Generated by Django 3.1.5 on 2021-01-17 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='HospitalAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('gender', models.TextField(max_length=10)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('appointment_on', models.DateTimeField()),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
