# Generated by Django 3.1.5 on 2021-01-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210118_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.TextField(blank=True, default='Not Done', max_length=12, null=True),
        ),
    ]
