# Generated by Django 3.1.5 on 2021-01-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20210118_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hospitalappointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
