# Generated by Django 3.1.5 on 2021-01-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20210120_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalappointment',
            name='status',
            field=models.TextField(blank=True, default='Not-Done', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.TextField(blank=True, default='Not-Done', max_length=12, null=True),
        ),
    ]
