# Generated by Django 3.1.5 on 2021-01-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='hospital/images/')),
                ('about', models.TextField(max_length=1000)),
                ('beds_available', models.IntegerField()),
                ('doctors_available', models.IntegerField()),
            ],
        ),
    ]
