# Generated by Django 3.1.5 on 2021-01-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210115_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
    ]
