# Generated by Django 3.1.5 on 2021-01-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210117_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospital/doctors/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='speciality',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
