# Generated by Django 3.1.5 on 2021-01-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('hospital', models.TextField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('address', models.TextField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('prescription', models.URLField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
