# Generated by Django 3.1.5 on 2021-01-17 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0006_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25)),
                ('company', models.TextField(max_length=25)),
                ('description', models.TextField(max_length=40)),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='medicine/images/')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospital')),
            ],
        ),
    ]
